"""Regenerate the design-token block in the upload pages' stylesheet.

Run from anywhere after changing `src/deltatrack/styles/tokens.css`, or after a rule in
`web/webapp/css/styles.css` or the processing tab in `web/webapp/js/compare.js` starts
or stops using a token:

    uv run python scripts/render_webapp_css.py

The upload pages are served as plain static files (FastAPI's `StaticFiles` mount, and
`web/webapp/.htaccess` for Apache), so their stylesheet has to be a committed file
rather than one built per request. Only the `:root` block between the GENERATED markers
is rewritten; the rules around it are edited by hand. `tests/test_webapp_css.py` fails if
the committed block is not what this script would write (#773).

The block holds the tokens the stylesheet's rules use plus those the processing tab
uses. The tab copies its colours from the upload page that opens it, so a token only the
tab uses still has to be declared here, or the tab would read an empty value.

Kept out of `render_examples.py` on purpose: tests drive that script's `main()` with
only its output folder redirected, so a write to a checkout path there would run on
every test run and could repair a stale block before the drift test looked at it.
"""

from __future__ import annotations

from pathlib import Path

from deltatrack.palette import referenced, root_block

PROJECT_ROOT = Path(__file__).resolve().parent.parent
WEBAPP = PROJECT_ROOT / "web" / "webapp"
STYLESHEET = WEBAPP / "css" / "styles.css"
PROCESSING_TAB = WEBAPP / "js" / "compare.js"

BEGIN = "/* BEGIN GENERATED by scripts/render_webapp_css.py. Do not edit by hand. */\n"
END = "/* END GENERATED */\n"


def render(stylesheet: str, processing_tab: str) -> str:
    """`stylesheet` with its generated block rewritten from the current tokens.

    Raises on missing, repeated or out-of-order markers rather than rewriting part of
    the file: a second block left stale would win the cascade over the fresh one.
    """
    if stylesheet.count(BEGIN) != 1 or stylesheet.count(END) != 1:
        raise ValueError(f"{STYLESHEET.name} must contain exactly one BEGIN and one END GENERATED marker")
    start = stylesheet.index(BEGIN) + len(BEGIN)
    end = stylesheet.index(END)
    if end < start:
        raise ValueError(f"{STYLESHEET.name}'s END GENERATED marker comes before its BEGIN marker")
    rules = stylesheet[:start] + stylesheet[end:]
    return stylesheet[:start] + root_block(referenced(rules + processing_tab)) + stylesheet[end:]


def main() -> None:
    STYLESHEET.write_text(render(STYLESHEET.read_text(), PROCESSING_TAB.read_text()))
    print(f"Wrote {STYLESHEET}")


if __name__ == "__main__":
    main()
